name: Harbor Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ci-skavys-harbor-crane-${{ github.ref }}-1
  cancel-in-progress: true

permissions:
  contents: read

env:
  extensions: simplexml, mbstring
  tools: composer, laravel/pint, nunomaduro/larastan, pestphp/pest
  ini_values: max_execution_time=180, date.timezone=Asia/Tbilisi
  cache_key: php-cache-v1

jobs:
  env-setup:
    timeout-minutes: 15
    if: github.event.pull_request.draft == false
    name: Set Variables
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.set-variables.outputs.cache-key }}
      extensions: ${{ steps.set-variables.outputs.extensions }}
      tools: ${{ steps.set-variables.outputs.tools }}
    steps:
      - name: Set variables
        id: set-variables
        run: |
          echo "::set-output name=cache-key::${{ env.cache_key }}"
          echo "::set-output name=extensions::${{ env.extensions }}"
          echo "::set-output name=tools::${{ env.tools }}"

  security-advisory:
    needs: [ env-setup ]
    name: Security Advisories
    uses: skavys/.github/.github/workflows/_security_advisory.yml@master
    with:
      cache_key: ${{ needs.env-setup.outputs.cache-key }}

  code-style:
    needs: [ env-setup ]
    name: Code Style
    uses: skavys/.github/.github/workflows/_code_style.yml@master
    with:
      cache_key: ${{ needs.env-setup.outputs.cache-key }}

  code-analyse:
    needs: [ env-setup ]
    name: Code Analyse
    uses: skavys/.github/.github/workflows/_code_analyse.yml@master
    with:
      cache_key: ${{ needs.env-setup.outputs.cache-key }}

  tests:
    needs: [ env-setup ]
    name: Tests
    uses: skavys/.github/.github/workflows/_tests.yml@master
    with:
      cache_key: ${{ needs.env-setup.outputs.cache-key }}
      extensions: ${{ needs.env-setup.outputs.extensions }}
      min_coverage: 80
